# fly.toml app configuration file generated for rickandmortyback on 2023-08-31T10:08:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rickandmortyback"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
